/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Luism
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        openFileButton = new javax.swing.JButton();
        executeButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        nextButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        registersTabbedPane = new javax.swing.JTabbedPane();
        registersPanel = new javax.swing.JPanel();
        pcRegLabel = new javax.swing.JLabel();
        acRegLabel = new javax.swing.JLabel();
        icRegLabel = new javax.swing.JLabel();
        axRegLabel = new javax.swing.JLabel();
        bxRegLabel = new javax.swing.JLabel();
        cxRegLabel = new javax.swing.JLabel();
        dxRegLabel = new javax.swing.JLabel();
        pcReg = new javax.swing.JLabel();
        acReg = new javax.swing.JLabel();
        irReg = new javax.swing.JLabel();
        axReg = new javax.swing.JLabel();
        bxReg = new javax.swing.JLabel();
        cxReg = new javax.swing.JLabel();
        dxReg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        memoryTabbedPane = new javax.swing.JTabbedPane();
        memoryGenPane = new javax.swing.JPanel();
        asmCodeLabel = new javax.swing.JLabel();
        dirLabel = new javax.swing.JLabel();
        binaryCodeLabel = new javax.swing.JLabel();
        memoryPanel = new javax.swing.JScrollPane();
        memoryMainPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(860, 540));

        openFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/open.png"))); // NOI18N
        openFileButton.setActionCommand("openFile");
        openFileButton.setBorder(null);
        openFileButton.setBorderPainted(false);
        openFileButton.setContentAreaFilled(false);
        openFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openFileButton.setDoubleBuffered(true);
        openFileButton.setFocusPainted(false);
        openFileButton.setPreferredSize(new java.awt.Dimension(32, 32));

        executeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/play.png"))); // NOI18N
        executeButton.setActionCommand("executeProgram");
        executeButton.setBorder(null);
        executeButton.setBorderPainted(false);
        executeButton.setContentAreaFilled(false);
        executeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        executeButton.setDoubleBuffered(true);
        executeButton.setEnabled(false);
        executeButton.setFocusPainted(false);
        executeButton.setPreferredSize(new java.awt.Dimension(32, 32));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/next.png"))); // NOI18N
        nextButton.setActionCommand("executeNextInstruction");
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.setDoubleBuffered(true);
        nextButton.setEnabled(false);
        nextButton.setFocusPainted(false);
        nextButton.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        registersPanel.setBackground(new java.awt.Color(255, 255, 255));

        pcRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pcRegLabel.setText("PC =");

        acRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acRegLabel.setText("AC =");

        icRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        icRegLabel.setText("IR  =");

        axRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        axRegLabel.setText("AX =");

        bxRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bxRegLabel.setText("BX =");

        cxRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cxRegLabel.setText("CX =");

        dxRegLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dxRegLabel.setText("DX =");

        pcReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pcReg.setText("0");

        acReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acReg.setText("0");

        irReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        irReg.setText("0");

        axReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        axReg.setText("0");

        bxReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bxReg.setText("0");

        cxReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxReg.setText("0");

        dxReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dxReg.setText("0");

        javax.swing.GroupLayout registersPanelLayout = new javax.swing.GroupLayout(registersPanel);
        registersPanel.setLayout(registersPanelLayout);
        registersPanelLayout.setHorizontalGroup(
            registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(registersPanelLayout.createSequentialGroup()
                        .addGroup(registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pcRegLabel)
                            .addComponent(acRegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icRegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(axRegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxRegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dxRegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bxRegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(irReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(axReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dxReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pcReg, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(bxReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        registersPanelLayout.setVerticalGroup(
            registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registersPanelLayout.createSequentialGroup()
                        .addComponent(pcReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irReg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registersPanelLayout.createSequentialGroup()
                        .addComponent(pcRegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acRegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icRegLabel)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registersPanelLayout.createSequentialGroup()
                        .addComponent(axReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dxReg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registersPanelLayout.createSequentialGroup()
                        .addComponent(axRegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxRegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxRegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dxRegLabel)))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        registersTabbedPane.addTab("Registers", registersPanel);

        memoryGenPane.setBackground(new java.awt.Color(255, 255, 255));

        asmCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asmCodeLabel.setText("Binary Code");

        dirLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dirLabel.setText("Dir");

        binaryCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        binaryCodeLabel.setText("ASM Code");

        memoryMainPane.setLayout(new java.awt.GridLayout(100, 0, 0, 5));
        memoryPanel.setViewportView(memoryMainPane);

        javax.swing.GroupLayout memoryGenPaneLayout = new javax.swing.GroupLayout(memoryGenPane);
        memoryGenPane.setLayout(memoryGenPaneLayout);
        memoryGenPaneLayout.setHorizontalGroup(
            memoryGenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoryGenPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoryGenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memoryPanel)
                    .addGroup(memoryGenPaneLayout.createSequentialGroup()
                        .addComponent(dirLabel)
                        .addGap(26, 26, 26)
                        .addComponent(asmCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(binaryCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        memoryGenPaneLayout.setVerticalGroup(
            memoryGenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoryGenPaneLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(memoryGenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirLabel)
                    .addComponent(asmCodeLabel)
                    .addComponent(binaryCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        memoryTabbedPane.addTab("Memory", memoryGenPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registersTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoryTabbedPane)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registersTabbedPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memoryTabbedPane))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel acReg;
    private javax.swing.JLabel acRegLabel;
    private javax.swing.JLabel asmCodeLabel;
    public javax.swing.JLabel axReg;
    private javax.swing.JLabel axRegLabel;
    private javax.swing.JLabel binaryCodeLabel;
    public javax.swing.JLabel bxReg;
    private javax.swing.JLabel bxRegLabel;
    public javax.swing.JLabel cxReg;
    private javax.swing.JLabel cxRegLabel;
    private javax.swing.JLabel dirLabel;
    public javax.swing.JLabel dxReg;
    private javax.swing.JLabel dxRegLabel;
    public javax.swing.JButton executeButton;
    private javax.swing.JLabel icRegLabel;
    public javax.swing.JLabel irReg;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel memoryGenPane;
    public javax.swing.JPanel memoryMainPane;
    public javax.swing.JScrollPane memoryPanel;
    private javax.swing.JTabbedPane memoryTabbedPane;
    public javax.swing.JButton nextButton;
    public javax.swing.JButton openFileButton;
    public javax.swing.JLabel pcReg;
    private javax.swing.JLabel pcRegLabel;
    private javax.swing.JPanel registersPanel;
    private javax.swing.JTabbedPane registersTabbedPane;
    // End of variables declaration//GEN-END:variables
}
