/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javafx.scene.paint.Color;

/**
 *
 * @author Luism
 */
public class MemoryRegisterPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form MemoryRegisterPanel
     */
    public MemoryRegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirLabel = new javax.swing.JLabel();
        binaryCodeLabel = new javax.swing.JLabel();
        asmCodeLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(30, 17));
        setLayout(null);

        dirLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dirLabel.setText("[05]");
        add(dirLabel);
        dirLabel.setBounds(0, 0, 40, 17);

        binaryCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        binaryCodeLabel.setText("0011 0001 00000101");
        add(binaryCodeLabel);
        binaryCodeLabel.setBounds(41, 0, 150, 17);

        asmCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asmCodeLabel.setText("MOV AX, 5");
        add(asmCodeLabel);
        asmCodeLabel.setBounds(195, 0, 370, 17);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel asmCodeLabel;
    public javax.swing.JLabel binaryCodeLabel;
    public javax.swing.JLabel dirLabel;
    // End of variables declaration//GEN-END:variables

}
